# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

trigger: none
pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

container: mlops

variables:
- group: devopsforai-aml-vg

steps:
- bash: 'pip install --user -r ./requirements.txt'
  displayName: 'Installing Dependencies'

- bash: '/home/vsts_azpcontainer/.local/bin/black ./utils --config ./black.toml'
  displayName: 'Running black Auto formatting for supporting function'

- bash: '/home/vsts_azpcontainer/.local/bin/isort ./utils --settings-file ./setup.cfg'
  displayName: 'Running isort for Auto imports arrangement for supporting function'
  
- template: code-quality-template.yml